### ISSUE TITLE
https://unpkg.com/extendable-media-recorder@4.2.23/build/es5/bundle.js throws error "Cannot read property 'mark' of undefined"

### ISSUE THREAD

**Issue by guest271314** [chrisguttandin/extendable-media-recorder#351]
```
<!DOCTYPE html>
<html>
  <head>
    <script src="https://unpkg.com/extendable-media-recorder@4.2.23/build/es5/bundle.js"></script>
  </head>
  <body>
  </body>
</html>
```

logs 

```
bundle.js:213 Uncaught TypeError: Cannot read property 'mark' of undefined
    at bundle.js:213
    at bundle.js:282
    at bundle.js:4
    at bundle.js:5
```

https://jsfiddle.net/orfctbx7/

**Comment by chrisguttandin** [comment]
Hi @guest271314,

unfortunately the package doesn't work with unpkg.com because the bundle.js file is not self contained. It contains all the JavaScript of the package itself but none of the dependencies. However it works with jspm.io.

I updated the jsfiddle to load the package via jspm.io: https://jsfiddle.net/1ystLvpu/5/

I hope that helps.
